alias grep="/bin/checks/grep_and_check.sh"
alias sed="/bin/checks/sed_and_check.sh"
alias awk="/bin/checks/awk_and_check.sh"
alias lab01="cd /home/regex_labs/lab01-grep_line_matching"
alias lab02="cd /home/regex_labs/lab02-grep_wildcards_groups"
alias lab03="cd /home/regex_labs/lab03-sed_substitution"
alias lab04="cd /home/regex_labs/lab04-awk_data_manipulation"
